name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"  # Her gün 18:00 UTC'de çalıştır
  workflow_dispatch: # Manuel olarak çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3  # Repoyu klonlar
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1  # 3D profil katkılarını oluşturur
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A .
          git commit -m "generated"
          git push
